name: Run Tests With Shard Loads Equalizer

on:
  workflow_dispatch:
    inputs:
      shardIndex:
        description: "Provide shard indices (comma-separated)"
        required: true
        default: "1,2,3,4,5,6,7,8,9,10"
      shardTotal:
        description: "Provide total number of shards"
        required: true
        default: 10

jobs:
  set_variable_for_shard_loads_equalizer:
    runs-on: ubuntu-latest
    outputs:
      shardIndexArray: ${{ steps.set_vars.outputs.shardIndexArray }}
    steps:
      - name: Set shardIndex array
        id: set_vars
        run: |
          shardIndexArray=$(echo '["'${{ github.event.inputs.shardIndex }}'"]' | sed 's/,/","/g')
          echo "shardIndexArray=$shardIndexArray" >> $GITHUB_ENV
          echo "::set-output name=shardIndexArray::$shardIndexArray"

  run_tests_with_shard_loads_equalizer:
    runs-on: ubuntu-latest
    needs: set_variable_for_shard_loads_equalizer
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        shardIndex: ${{ fromJson(needs.set_variable_for_shard_loads_equalizer.outputs.shardIndexArray) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Set shardTotal and AUTO environment variables
        run: |
          echo "SHARD_TOTAL=${{ github.event.inputs.shardTotal }}" >> $GITHUB_ENV
          echo "AUTO=false" >> $GITHUB_ENV  # Set AUTO to false
      - name: Install dependencies
        run: npm install
      - name: Get test names
        id: getTestNames
        run: |
          test_names=$(node -e 'import("shard-loads-equalizer").then(module => console.log(module.shardLoadsEqualizer(${{ matrix.shardIndex }},${{ github.event.inputs.shardTotal }}))).catch(err => console.error(err))')
          echo "test_names=$test_names" >> $GITHUB_ENV
      - name: Run Playwright tests
        run: |
          npx playwright test --grep "${{ env.test_names }}"

  # This is Optional, my intention is to run the tests without shard loads equalizer to show the difference in execution time
  set_variable_for_normal_tests:
    needs: run_tests_with_shard_loads_equalizer
    runs-on: ubuntu-latest
    outputs:
      shardIndexArray: ${{ steps.set_variable_for_normal_test.outputs.shardIndexArray }}
    steps:
      - name: Set shardIndex array
        id: set_variable_for_normal_test
        run: |
          shardIndexArray=$(echo '["'${{ github.event.inputs.shardIndex }}'"]' | sed 's/,/","/g')
          echo "shardIndexArray=$shardIndexArray" >> $GITHUB_ENV
          echo "::set-output name=shardIndexArray::$shardIndexArray"

  run_tests_without_shard_loads_equalizer:
    needs:
      - set_variable_for_normal_tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: ${{ fromJson(needs.set_variable_for_normal_tests.outputs.shardIndexArray) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Set shardTotal and AUTO environment variables
        run: |
          echo "shardTotal=${{ matrix.shardTotal }}" >> $GITHUB_ENV
          echo "AUTO=false" >> $GITHUB_ENV  # Set AUTO to false for this job as well
      - name: Install dependencies
        run: npm install
      - name: Run Playwright tests
        run: |
          npx playwright test --shard=${{ matrix.shardIndex }}/${{ github.event.inputs.shardTotal }}
